import React from 'react';
import { Link } from 'react-router-dom';
import { BookOpen } from 'lucide-react';

export default function Privacy() {
  return (
    <div className="min-h-screen bg-cream px-4 py-12 text-dark font-sans">
      <div className="max-w-[700px] mx-auto bg-white/60 p-5 sm:p-12 rounded-3xl border border-border-theme shadow-theme-md">
        
        <Link to="/" className="inline-flex items-center gap-2 text-primary font-sub font-bold uppercase tracking-wider text-xs mb-8 hover:text-primary-hover transition-colors">
          <BookOpen size={14}/> Safarnama
        </Link>
        
        <h1 className="text-2xl sm:text-3xl font-heading font-semibold text-primary mb-2">Privacy Policy</h1>
        <div className="text-dark/40 text-[10px] font-sub uppercase tracking-wider mb-8 flex flex-wrap items-center gap-x-2 gap-y-1">
          <span>Last Updated: January 2026</span>
          <span className="text-dark/20">•</span>
          <span>
            Contact:{' '}
            <a href="mailto:help.safarnama@gmail.com" className="underline hover:text-rose-safarnama font-semibold break-all">
              help.safarnama@gmail.com
            </a>
          </span>
        </div>

        <div className="text-dark/70 leading-relaxed space-y-6">
          <section>
            <h2 className="font-heading text-lg font-semibold text-primary mb-1.5">1. Introduction</h2>
            <p className="text-sm font-sans">Welcome to Safarnama.</p>
            <p className="text-sm font-sans mt-2">Safarnama is a shared timeline platform that allows couples, friends, and families to capture and preserve meaningful memories together.</p>
            <p className="text-sm font-sans mt-2">Your privacy matters to us. This Privacy Policy explains what information we collect, how we use it, and how we protect it.</p>
          </section>

          <section>
            <h2 className="font-heading text-lg font-semibold text-primary mb-2">2. Information We Collect</h2>
            
            <h3 className="font-heading text-base font-semibold text-primary mt-4 mb-1">A. Account Information</h3>
            <p className="text-sm font-sans">When you sign in using Google OAuth, we receive your name, email address, and Google user ID. We do not collect passwords.</p>
            
            <h3 className="font-heading text-base font-semibold text-primary mt-4 mb-1">B. Content You Create</h3>
            <p className="text-sm font-sans">When using Safarnama, we store timeline entries (text, dates, titles), images and videos you upload, event categories and metadata, and collaboration permissions.</p>
            
            <h3 className="font-heading text-base font-semibold text-primary mt-4 mb-1">C. Google Drive Access</h3>
            <p className="text-sm font-sans">Safarnama may request permission to create and manage files generated by Safarnama inside your Google Drive.</p>
            <p className="text-sm font-sans mt-2">We do <strong>not</strong> access unrelated files, scan your Drive, or read private documents outside app-created files.</p>
            
            <h3 className="font-heading text-base font-semibold text-primary mt-4 mb-1">D. Payment Information</h3>
            <p className="text-sm font-sans">Payments are processed securely through Dodo Payments. We store Order ID, Payment ID, subscription plan type, and plan expiry date. We do <strong>not</strong> store card details, UPI credentials, or banking information.</p>
            
            <h3 className="font-heading text-base font-semibold text-primary mt-4 mb-1">E. Technical Information</h3>
            <p className="text-sm font-sans">We may collect IP address, device/browser type, and basic usage logs to maintain security and improve performance.</p>
          </section>

          <section>
            <h2 className="font-heading text-lg font-semibold text-primary mb-1.5">3. How We Use Your Information</h2>
            <p className="text-sm font-sans">We use collected data to provide timeline and collaboration features, enable secure authentication, process subscription payments, enforce plan limits, improve service reliability, and prevent abuse or misuse.</p>
            <p className="text-sm font-sans mt-2 font-semibold text-dark">We do not sell your personal data.</p>
          </section>

          <section>
            <h2 className="font-heading text-lg font-semibold text-primary mb-1.5">4. Data Storage</h2>
            <p className="text-sm font-sans">Your data is stored using Firebase (Google Cloud), Google Drive (for uploaded files), and Dodo Payments (for payment processing). All data is transmitted securely via HTTPS encryption.</p>
          </section>

          <section>
            <h2 className="font-heading text-lg font-semibold text-primary mb-1.5">5. Collaboration & Shared Access</h2>
            <p className="text-sm font-sans">Safarnama allows view-only access via share codes and edit access via collaboration links. You are responsible for who you share access with.</p>
          </section>

          <section>
            <h2 className="font-heading text-lg font-semibold text-primary mb-1.5">6. Data Retention</h2>
            <p className="text-sm font-sans">Your data remains stored until you delete your account, you request deletion, or we are legally required to remove it.</p>
          </section>

          <section>
            <h2 className="font-heading text-lg font-semibold text-primary mb-1.5">7. Your Rights (India – DPDP Act 2023)</h2>
            <p className="text-sm font-sans">You may request access to your stored data, request correction, request deletion, or withdraw consent.</p>
            <p className="text-sm font-sans mt-2">Contact us at: <a href="mailto:help.safarnama@gmail.com" className="underline hover:text-rose-safarnama font-semibold">help.safarnama@gmail.com</a></p>
          </section>

          <section>
            <h2 className="font-heading text-lg font-semibold text-primary mb-1.5">8. Google API Services Disclosure</h2>
            <p className="text-sm font-sans">Safarnama's use and transfer of information received from Google APIs adheres to the <a href="https://developers.google.com/terms/api-services-user-data-policy" target="_blank" rel="noopener noreferrer" className="underline hover:text-rose-safarnama">Google API Services User Data Policy</a>, including Limited Use requirements.</p>
          </section>

          <section>
            <h2 className="font-heading text-lg font-semibold text-primary mb-1.5">9. Updates</h2>
            <p className="text-sm font-sans">We may update this Privacy Policy from time to time. Updates will be reflected by the "Last Updated" date above.</p>
          </section>
        </div>

        <div className="mt-12 pt-6 border-t border-border-theme flex flex-wrap gap-x-4 gap-y-2 text-[10px] font-sub font-bold uppercase tracking-wider text-dark/40">
          <Link to="/terms"      className="hover:text-primary">Terms</Link>
          <Link to="/refund"     className="hover:text-primary">Refund Policy</Link>
          <Link to="/pricing"    className="hover:text-primary">Pricing</Link>
          <Link to="/google-api" className="hover:text-primary">Google API</Link>
          <Link to="/about"      className="hover:text-primary transition-colors">About</Link>
          <Link to="/"           className="hover:text-primary sm:ml-auto">← Back to app</Link>
        </div>
      </div>
    </div>
  );
}
