import React from 'react';
import { Link } from 'react-router-dom';
import { BookOpen } from 'lucide-react';

export default function Privacy() {
  return (
    <div className="min-h-screen bg-white px-4 py-12">
      <div className="max-w-[700px] mx-auto">
        <Link to="/" className="inline-flex items-center gap-2 text-rose-400 text-sm mb-8 hover:text-rose-500 transition-colors">
          <BookOpen size={14}/> Safarnama
        </Link>
        <h1 className="text-3xl font-bold text-transparent bg-clip-text bg-gradient-to-r from-amber-400 via-rose-500 to-pink-500 mb-2">Privacy Policy</h1>
        <p className="text-gray-400 text-sm mb-10">Last Updated: January 2026 &nbsp;·&nbsp; Contact: <a href="mailto:vijendra9753@gmail.com" className="underline hover:text-rose-400">vijendra9753@gmail.com</a></p>

        <div className="text-gray-600 leading-relaxed space-y-8">

          <section>
            <h2 className="text-lg font-semibold text-gray-700 mb-2">1. Introduction</h2>
            <p>Welcome to Safarnama.</p>
            <p className="mt-2">Safarnama is a shared timeline platform that allows couples, friends, and families to capture and preserve meaningful memories together.</p>
            <p className="mt-2">Your privacy matters to us. This Privacy Policy explains what information we collect, how we use it, and how we protect it.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-gray-700 mb-2">2. Information We Collect</h2>
            <h3 className="font-semibold text-gray-600 mt-3 mb-1">A. Account Information</h3>
            <p>When you sign in using Google OAuth, we receive your name, email address, and Google user ID. We do not collect passwords.</p>

            <h3 className="font-semibold text-gray-600 mt-3 mb-1">B. Content You Create</h3>
            <p>When using Safarnama, we store timeline entries (text, dates, titles), images and videos you upload, event categories and metadata, and collaboration permissions. This data is required for the platform to function.</p>

            <h3 className="font-semibold text-gray-600 mt-3 mb-1">C. Google Drive Access</h3>
            <p>Safarnama may request permission to create and manage files generated by Safarnama inside your Google Drive.</p>
            <p className="mt-2">We do <strong>not</strong> access unrelated files, scan your Drive, or read private documents outside app-created files. You may revoke access anytime via your Google account settings.</p>

            <h3 className="font-semibold text-gray-600 mt-3 mb-1">D. Payment Information</h3>
            <p>Payments are processed securely through Razorpay. We store Order ID, Payment ID, subscription plan type, and plan expiry date.</p>
            <p className="mt-2">We do <strong>not</strong> store card details, UPI credentials, or banking information.</p>

            <h3 className="font-semibold text-gray-600 mt-3 mb-1">E. Technical Information</h3>
            <p>We may collect IP address, device/browser type, and basic usage logs to maintain security and improve performance.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-gray-700 mb-2">3. How We Use Your Information</h2>
            <p>We use collected data to provide timeline and collaboration features, enable secure authentication, process subscription payments, enforce plan limits, improve service reliability, and prevent abuse or misuse.</p>
            <p className="mt-2 font-medium text-gray-700">We do not sell your personal data.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-gray-700 mb-2">4. Data Storage</h2>
            <p>Your data is stored using Firebase (Google Cloud), Google Drive (for uploaded files), and Razorpay (for payment processing). All data is transmitted securely via HTTPS encryption.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-gray-700 mb-2">5. Collaboration & Shared Access</h2>
            <p>Safarnama allows view-only access via share codes and edit access via collaboration links. You are responsible for who you share access with. Safarnama is not responsible for disputes between collaborators.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-gray-700 mb-2">6. Data Retention</h2>
            <p>Your data remains stored until you delete your account, you request deletion, or we are legally required to remove it. Upon deletion, timeline content and associated data will be removed.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-gray-700 mb-2">7. Your Rights (India – DPDP Act 2023)</h2>
            <p>You may request access to your stored data, request correction, request deletion, or withdraw consent.</p>
            <p className="mt-2">Contact us at: <a href="mailto:vijendra9753@gmail.com" className="underline hover:text-rose-400">vijendra9753@gmail.com</a></p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-gray-700 mb-2">8. Google API Services Disclosure</h2>
            <p>Safarnama's use and transfer of information received from Google APIs adheres to the <a href="https://developers.google.com/terms/api-services-user-data-policy" target="_blank" rel="noopener noreferrer" className="underline hover:text-rose-400">Google API Services User Data Policy</a>, including Limited Use requirements.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-gray-700 mb-2">9. Updates</h2>
            <p>We may update this Privacy Policy from time to time. Updates will be reflected by the "Last Updated" date above.</p>
          </section>

        </div>

        <div className="mt-12 pt-6 border-t border-gray-100 flex gap-4 text-xs text-gray-400">
          <Link to="/terms"      className="hover:text-rose-400">Terms</Link>
          <Link to="/refund"     className="hover:text-rose-400">Refund Policy</Link>
          <Link to="/google-api" className="hover:text-rose-400">Google API</Link>
          <Link to="/"           className="hover:text-rose-400 ml-auto">← Back to app</Link>
        </div>
      </div>
    </div>
  );
}
