export const THEMES = [
  {
    id: 'love', name: 'Classic 💕',
    gradient: 'from-cream via-cream to-cream-dark',
    header: 'from-primary to-accent',
    banner: 'from-primary to-primary-hover',
    counter: 'text-primary', counterBorder: 'border-border-theme',
    tabActive: 'bg-primary text-cream hover:bg-primary-hover',
    fab: 'bg-primary hover:bg-primary-hover text-cream shadow-theme-md',
    heart: 'text-rose-safarnama', badge: 'bg-rose-safarnama/10 text-rose-safarnama',
    dot: 'bg-rose-safarnama', timeline: 'from-primary/20 to-accent/20',
    eventBg: 'bg-white/80', dateBadge: 'text-accent bg-cream border-border-theme',
    float: { emoji: '❤️', colors: ['text-rose-safarnama/30', 'text-accent/30'], animation: 'float', show: true },
    accentBg: 'bg-primary/5', accentText: 'text-primary', accentBorder: 'border-border-theme', accentHover: 'hover:bg-primary/10', accentHoverBtn: 'hover:bg-primary/20',
    btnPrimary: 'bg-primary hover:bg-primary-hover text-cream shadow-theme-sm',
  },
  {
    id: 'ocean', name: 'Ocean 🌊',
    gradient: 'from-cream via-cream to-cream-dark',
    header: 'from-primary to-accent',
    banner: 'from-primary to-primary-hover',
    counter: 'text-primary', counterBorder: 'border-border-theme',
    tabActive: 'bg-primary text-cream hover:bg-primary-hover',
    fab: 'bg-primary hover:bg-primary-hover text-cream shadow-theme-md',
    heart: 'text-primary', badge: 'bg-primary/10 text-primary',
    dot: 'bg-primary', timeline: 'from-primary/20 to-accent/20',
    eventBg: 'bg-white/80', dateBadge: 'text-accent bg-cream border-border-theme',
    float: { emoji: '🫧', colors: ['text-primary/30', 'text-accent/30'], animation: 'floatSway', show: true },
    accentBg: 'bg-primary/5', accentText: 'text-primary', accentBorder: 'border-border-theme', accentHover: 'hover:bg-primary/10', accentHoverBtn: 'hover:bg-primary/20',
    btnPrimary: 'bg-primary hover:bg-primary-hover text-cream shadow-theme-sm',
  },
  {
    id: 'forest', name: 'Forest 🌿',
    gradient: 'from-cream via-cream to-cream-dark',
    header: 'from-primary to-accent',
    banner: 'from-primary to-primary-hover',
    counter: 'text-primary', counterBorder: 'border-border-theme',
    tabActive: 'bg-primary text-cream hover:bg-primary-hover',
    fab: 'bg-primary hover:bg-primary-hover text-cream shadow-theme-md',
    heart: 'text-primary', badge: 'bg-primary/10 text-primary',
    dot: 'bg-primary', timeline: 'from-primary/20 to-accent/20',
    eventBg: 'bg-white/80', dateBadge: 'text-accent bg-cream border-border-theme',
    float: { emoji: '🍃', colors: ['text-primary/30', 'text-accent/30'], animation: 'floatLeaf', show: true },
    accentBg: 'bg-primary/5', accentText: 'text-primary', accentBorder: 'border-border-theme', accentHover: 'hover:bg-primary/10', accentHoverBtn: 'hover:bg-primary/20',
    btnPrimary: 'bg-primary hover:bg-primary-hover text-cream shadow-theme-sm',
  },
  {
    id: 'sunset', name: 'Sunset 🌅',
    gradient: 'from-cream via-cream to-cream-dark',
    header: 'from-primary to-accent',
    banner: 'from-primary to-primary-hover',
    counter: 'text-primary', counterBorder: 'border-border-theme',
    tabActive: 'bg-primary text-cream hover:bg-primary-hover',
    fab: 'bg-primary hover:bg-primary-hover text-cream shadow-theme-md',
    heart: 'text-rose-safarnama', badge: 'bg-rose-safarnama/10 text-rose-safarnama',
    dot: 'bg-rose-safarnama', timeline: 'from-primary/20 to-accent/20',
    eventBg: 'bg-white/80', dateBadge: 'text-accent bg-cream border-border-theme',
    float: { emoji: '✨', colors: ['text-primary/30', 'text-accent/30'], animation: 'floatSpark', show: true },
    accentBg: 'bg-primary/5', accentText: 'text-primary', accentBorder: 'border-border-theme', accentHover: 'hover:bg-primary/10', accentHoverBtn: 'hover:bg-primary/20',
    btnPrimary: 'bg-primary hover:bg-primary-hover text-cream shadow-theme-sm',
  },
  {
    id: 'galaxy', name: 'Galaxy 🌌',
    gradient: 'from-cream via-cream to-cream-dark',
    header: 'from-primary to-accent',
    banner: 'from-primary to-primary-hover',
    counter: 'text-primary', counterBorder: 'border-border-theme',
    tabActive: 'bg-primary text-cream hover:bg-primary-hover',
    fab: 'bg-primary hover:bg-primary-hover text-cream shadow-theme-md',
    heart: 'text-primary', badge: 'bg-primary/10 text-primary',
    dot: 'bg-primary', timeline: 'from-primary/20 to-accent/20',
    eventBg: 'bg-white/80', dateBadge: 'text-accent bg-cream border-border-theme',
    float: { emoji: '⭐', colors: ['text-primary/30', 'text-accent/30'], animation: 'floatStar', show: true },
    accentBg: 'bg-primary/5', accentText: 'text-primary', accentBorder: 'border-border-theme', accentHover: 'hover:bg-primary/10', accentHoverBtn: 'hover:bg-primary/20',
    btnPrimary: 'bg-primary hover:bg-primary-hover text-cream shadow-theme-sm',
  },
  {
    id: 'monochrome', name: 'Minimal ◻️',
    gradient: 'from-cream via-cream to-cream-dark',
    header: 'from-primary to-accent',
    banner: 'from-primary to-primary-hover',
    counter: 'text-primary', counterBorder: 'border-border-theme',
    tabActive: 'bg-primary text-cream hover:bg-primary-hover',
    fab: 'bg-primary hover:bg-primary-hover text-cream shadow-theme-md',
    heart: 'text-primary', badge: 'bg-primary/10 text-primary',
    dot: 'bg-primary', timeline: 'from-primary/20 to-accent/20',
    eventBg: 'bg-white/80', dateBadge: 'text-accent bg-cream border-border-theme',
    float: { show: false },
    accentBg: 'bg-primary/5', accentText: 'text-primary', accentBorder: 'border-border-theme', accentHover: 'hover:bg-primary/10', accentHoverBtn: 'hover:bg-primary/20',
    btnPrimary: 'bg-primary hover:bg-primary-hover text-cream shadow-theme-sm',
  },
];

export const getTheme = (id) => THEMES.find(t => t.id === id) || THEMES[0];